# Plugins
plugins:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "EBL 2019"
email: "email"
description: "19th Brazilian Logic Conference (EBL 2019)"
baseurl: ""
url: "https://brunobruck.github.io"
permalink: "/blog/:title"

# Head
metaKeywords: "event, ebl, logic, mathematics, school, conference"

# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/blog/call-for-papers", text: "Call for Papers"}
 - {permalink: "/blog/important-dates", text: "Important Dates"}
 # - {permalink: "/registration/", text: "Registration"}
 - {permalink: "/schedule/", text: "Program"}
 - {permalink: "/blog/accommodation", text: "Accommodation"}

# Hero Block
heroImage: "Litoral.jpg"
heroTitle: "EBL 2019 <typeout>"
eventDate: "May 6-10, 2019"
typeoutTextValues: '"", "| João Pessoa", "| Brazil"'
# typeoutFallback: "Season"
heroButtons:
 # - {link: "https://bit.ly/", text: "Call for Papers"}
 - {permalink: "/blog/call-for-papers", text: "Call for Papers"}
 # - {permalink: "/registration", text: "Registration"}

# About Block
aboutTitle: "About the 19th Brazilian Logic Conference"
aboutBlock:
 - {title: "Conference", image: "conference.jpg", text: "The Brazilian Logic Conference (EBL) is a traditional event of the Brazilian Logic Society (SBL). It has been occurring since 1979 and congregates logicians of different fields and the meeting is an important moment for the Brazilian and South-American community to join together and engage in a discussion about the state-of-art of their subject." }
 - {title: "Logic School", image: "school.jpg", text: "The Logic School is a parallel event to the EBL aimed (mainly) at undergraduate and graduate students. It offers tutorials on different logical subject matters by world renowned experts." }
 # - {title: "Hackathon", image: "hackathon.jpg", text: "Full-day freestyle hackathon! Want some real team building on friday? Grab your team and join our hackathon!" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "200", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "40", specialCharacter: "+", info: "hours", detail: "of presentations"}
 - {count: "10", specialCharacter: "+", info: "speakers", detail: "from the country and abroad"}
 - {count: "10", specialCharacter: "", info: "hours", detail: "of Tutorials"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Rockstar speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Hotel Nord Luxxor Tambaú"
eventLocationLink: "http://www.nordhoteis.com.br/en/hotel/nord-luxxor-tambau/"
eventStreetAddress: "Av. Alm. Tamandaré, 740 - Tambaú, João Pessoa"
eventAddressLocality: "Hotel Nord Luxxor Tambaú"
eventAddressLocalityRegion: "Paraíba"
eventAddressCountry: "Brazil"
# eventStartTime: "2014-10-25T10:00"
# eventDoorTime: "09:00"
# eventEndTime: "2014-10-25T20:00", 
eventPlaceCoordinates: "-7.116387, -34.823286"
mapCenterCoordinates: "-7.116387, -34.823286"
mapMobileCenterCoordinates: "-7.116387, -34.823286"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "hotel_1.jpg"
venueSmallImage1: "hotel_2.jpg"
venueSmallImage2: "hotel_3.jpg"
venueTitle: "Hotel Nord Luxxor Tambaú"
venueFeatures: ["Conference rooms", "Restaurant", "Close to the beach"]

# Tweets Feed Block
# tweetsFeedImage: "twitter-feed.jpg"
# tweetsFeedTitle: "What's Up?"
# twitterHashTag: "devfest"
# twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
# organizersTitle: "Organizers"
# partnersTitle: "Partners"
# partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
# subscribeImage: "subscribe.jpg"
# subscribeTitle: "Subscribe for updates"
# subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
# subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Registration fees"
ticketsInfo: "REGISTRATIONS WILL BE AVAILABLE SOON. Tickets grant access to all conference sections and coffee breaks. Accommodation and lunch are NOT included in the ticket price."
ticketsOffers:
 -
  name: "Early Bird"
  tariffs:
    - {name: "Faculty members/Researchers", price: "400", currency: "BRL"}
    - {name: "Faculty members/Researchers (SBL members)", price: "120", currency: "BRL"}
    - {name: "Graduate Students", price: "150", currency: "BRL"}
    - {name: "Graduate Students (SBL members)", price: "80", currency: "BRL"}
  additionalInfo: "Valid for registrations performed until March 10th"
 -
  name: "Late registration"
  tariffs:
    - {name: "Faculty members/Researchers", price: "550", currency: "BRL"}
    - {name: "Faculty members/Researchers (SBL members)", price: "250", currency: "BRL"}
    - {name: "Graduate Students", price: "200", currency: "BRL"}
    - {name: "Graduate Students (SBL members)", price: "120", currency: "BRL"}
  additionalInfo: "After March 10th"
 -
  name: "Undergraduate Students"
  tariffs:
    - {name: "FREE", price: "", currency: ""}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
# discusShortName: "devfestua"

# Speakers List Block
showSessions: true

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
# findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "-7.137615, -34.845175"
logisticsMapMobileCenterCoordinates: "-7.137615, -34.845175"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "orla.jpg"
directionDetailsTitle: "Get around João Pessoa"
directionDetailsCards:
 - {title: "From the Airport", information: 'Soon'}
 - {title: "Public Transit", information: 'Soon'}
 - {title: "Hotels", information: 'Soon'}